-- Run this in Snowflake first
CREATE DATABASE SNOWPIPE_DEMO
DATA_RETENTION_TIME_IN_DAYS = 1
COMMENT = 'Database for Snowpipe demo project';

USE DATABASE SNOWPIPE_DEMO;

CREATE SCHEMA DATA_INGESTION
WITH MANAGED ACCESS
COMMENT = 'Schema for raw data ingestion';


USE SCHEMA DATA_INGESTION;

-- 1. Create file format
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null')
    EMPTY_FIELD_AS_NULL = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

-- 2. Create stage (replace credentials)
CREATE OR REPLACE STAGE MY_S3_STAGE
  URL = 's3://snowpipe-demo-ss-source/transactions/'
  CREDENTIALS = (
    AWS_KEY_ID = ''
    AWS_SECRET_KEY = ''
  )
  FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

-- 3. Create target table (if not exists)
CREATE OR REPLACE TABLE CUSTOMER_TRANSACTIONS (
    TRANSACTION_ID STRING NOT NULL,
    CUSTOMER_ID STRING,
    TRANSACTION_DATE TIMESTAMP_NTZ,
    AMOUNT FLOAT,
    PRODUCT_CATEGORY STRING,
    PAYMENT_METHOD STRING,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()

);

-- 4. Create the pipe
CREATE OR REPLACE PIPE CUSTOMER_TRANSACTIONS_PIPE
AUTO_INGEST = TRUE
COMMENT = 'Auto-ingest pipe for transaction data'
AS
COPY INTO CUSTOMER_TRANSACTIONS (
    TRANSACTION_ID,
    CUSTOMER_ID,
    TRANSACTION_DATE,
    AMOUNT,
    PRODUCT_CATEGORY,
    PAYMENT_METHOD
)
FROM @MY_S3_STAGE
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT')
PATTERN = '.*transactions.*[.]csv';



